name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache-dependency-path: go.sum

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true
          args: --config=./.golangci.yaml
